### ISSUE TITLE
Canarie API 0.4.3 : ModuleNotFoundError: No module named 'wsgi'

### ISSUE THREAD

**Issue by matprov** [Ouranosinc/CanarieAPI#9]

**Comment by fmigneault** [comment]
Possible that it is caused by an old/invalid docker command override?

This is valid:
https://github.com/Ouranosinc/CanarieAPI/blob/529d5807b19254d3f958a2da6f4341426d54cf6f/Dockerfile#L49

While docs still indicate an incorrect path unless the package is sourced in python path:
https://github.com/Ouranosinc/CanarieAPI/blob/529d5807b19254d3f958a2da6f4341426d54cf6f/docs/usage.rst
